### ISSUE TITLE
goatools.associations.read_gaf function exiting early on illegal GAF lines (should just ignore)

### ISSUE THREAD

**Issue by lolo-1992** [tanghaibao/goatools#95]
Hi there!

The function read_gaf from goatools.associations can't read version 2.1 of 'gaf' files from the Gene Ontology Consortium (current version 2.1). (The functions works fine with version 2.0.)

Trying to read gaf files from the geneontology website give this traceback:
`from goatools.associations import read_gaf
associations = read_gaf("http://geneontology.org/gene-associations/gene_association.tair.gz")`

```
TypeError                                 Traceback (most recent call last)
<ipython-input-10-1667bc12273f> in <module>()

----> 6 associations = read_gaf("http://geneontology.org/gene-associations/gene_association.tair.gz")

~/anaconda3/lib/python3.6/site-packages/goatools/associations.py in read_gaf(fin_gaf, prt, **kws)
    157     id2gos = defaultdict(set)
    158     # Optional detailed associations split by taxid and having both ID2GOs & GO2IDs
--> 159     gafobj = GafReader(fin_gaf, hdr_only, prt)
    160     # Optionally specify a subset of GOs based on their evidence.
    161     # By default, return id2gos. User can cause go2geneids to be returned by:

~/anaconda3/lib/python3.6/site-packages/goatools/anno/gaf_reader.py in __init__(self, filename, hdr_only, prt)
     64         # Initialize associations and header information
     65         self.hdr = None
---> 66         self.associations = self.read_gaf(filename, hdr_only, prt) if filename is not None else []
     67 
     68     def prt_summary_anno2ev(self, prt=sys.stdout):

~/anaconda3/lib/python3.6/site-packages/goatools/anno/gaf_reader.py in read_gaf(self, fin_gaf, hdr_only, prt)
    141         hdrobj = GafHdr()
    142         ifstrm = nopen(fin_gaf)
--> 143         for line in ifstrm:
    144             # Read header
    145             if ntgafobj is None:

~/anaconda3/lib/python3.6/site-packages/goatools/base.py in ungzipper(fh, blocksize)
     98     import zlib
     99     uzip = zlib.decompressobj(16 + zlib.MAX_WBITS)
--> 100     data = uzip.decompress(fh.read(blocksize)).split("\n")
    101 
    102     while len(data[0]):

TypeError: a bytes-like object is required, not 'str'
```

And using an extracted file, I get this traceback:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-12-991e9ff245b5> in <module>()

----> 5 associations = read_gaf('/home/laurent/Downloads/tair_merged.gaf')

~/anaconda3/lib/python3.6/site-packages/goatools/associations.py in read_gaf(fin_gaf, prt, **kws)
    157     id2gos = defaultdict(set)
    158     # Optional detailed associations split by taxid and having both ID2GOs & GO2IDs
--> 159     gafobj = GafReader(fin_gaf, hdr_only, prt)
    160     # Optionally specify a subset of GOs based on their evidence.
    161     # By default, return id2gos. User can cause go2geneids to be returned by:

~/anaconda3/lib/python3.6/site-packages/goatools/anno/gaf_reader.py in __init__(self, filename, hdr_only, prt)
     64         # Initialize associations and header information
     65         self.hdr = None
---> 66         self.associations = self.read_gaf(filename, hdr_only, prt) if filename is not None else []
     67 
     68     def prt_summary_anno2ev(self, prt=sys.stdout):

~/anaconda3/lib/python3.6/site-packages/goatools/anno/gaf_reader.py in read_gaf(self, fin_gaf, hdr_only, prt)
    156             # Read data
    157             if ntgafobj is not None:
--> 158                 flds = self._split_line(line, exp_numcol)
    159                 ntgaf = self._get_ntgaf(ntgafobj, flds, ver)
    160                 ga_lst.append(ntgaf)

~/anaconda3/lib/python3.6/site-packages/goatools/anno/gaf_reader.py in _split_line(line, exp_numcol)
    170         line = line.rstrip('\r\n')
    171         flds = re.split('\t', line)
--> 172         assert len(flds) == exp_numcol, "UNEXPECTED NUMBER OF COLUMNS"
    173         return flds
    174 

AssertionError: UNEXPECTED NUMBER OF COLUMNS
```

Best,

Laurent

**Comment by dvklopfenstein** [comment]
Laurent,

Thank you for your interest in GOATOOLS and taking the time to contact us regarding reading the GAF files.

  1. If you did a 'git clone' to download GOATOOLS, could you do a 'git pull' to get the latest code and then re-try reading the gaf file? We have noticed that lately some GAF files have had 'inconsistencies' not seen before. We have seen the column error and added code to address it. Another new item we have seen is some GAF files lately have some lines that no longer have the "required" DB_Symbol. We have recently added code to read gaf files despite these new inconsistencies. Now, instead of reporting an illegal line and ending the program, we ignore the illegal line. In the case of DB_Symbol, we added an override so you can read GAF lines that are missing DB_Symbol if you want to.

  2. Can you send us the gaf file that when read, produces the error?
 
Thank you again for using GOATOOLS. The gaf error may already be addressed. If it is, then I will ask that we release a new GOATOOLS version into PyPI, as the current version does not have our latest GAF updates.

**Comment by lolo-1992** [comment]
Hi,
I didn't download Goatools with a git clone, but with PyPI indeed.
here is the file producing the error: https://we.tl/WjhdYvSMel

**Comment by dvklopfenstein** [comment]
I just loaded your gaf file with our latest code:
```
  READ 260,258 associations: tair_merged.gaf
  27,226 IDs found in tair_merged.gaf
```
We do see 24 lines ignored due to a missing DB_ID . These messages look like this:
```
**ERROR: UNEXPECTED REQUIRED VAL() FOR COL(0):DB: DB() DB_ID()
**WARNING: IGNORED tair_merged.gaf[225854]:
		At1g21570		GO:0003723	PAINT_REF:23102	IBA	PANTHER:PTN000559726	F	Zinc finger CCCH domain-containing protein 7	UniProtKB:Q3ED78|PTN000559779	protein	taxon:3702	20170427	GO_Central		
```
This has been a new thing we are seeing in the GAF files. DB_ID is definitely required, so these 24 lines will be ignored. The DB_ID lines in tair_merged.gaf have the format of 'locus:NNNNN' like this:
```
 11 GO IDs associated with locus:2050064
  3 GO IDs associated with locus:2180662
 10 GO IDs associated with locus:2050069
  1 GO IDs associated with locus:1009023190
  3 GO IDs associated with locus:1009023438
  1 GO IDs associated with locus:1009023439
```

I will ask @tanghaibao to please update PyPI with our latest code as soon as possible so that you may be working again quickly. If you want to clone, you can get the latest code immediately.

Thank you for taking the time to report this issue. I will close it when PyPI is updated. Thank you for using GOATOOLS.

**Comment by dvklopfenstein** [comment]
One more note...

Please download the gaf file and uncompress it before reading it.
I took the code out that automatically downloads it from the web and uncompresses it in the last version.
Please let us know if this an issue for you and you would prefer that the option remain to read the file directly from the web as a compressed file.

**Comment by lolo-1992** [comment]
Thank you very much for your help.
I don't need the option of downloading gaf files from the web. However, as you removed this functionality, you should change the line in the notebook "semantic similarity" (3rd block).

**Comment by dvklopfenstein** [comment]
The latest code is now available in PyPI. I am going to close this issue. If you see anything else, please do open a new issue.

Thanks for the heads up on changing the documentation. Thank you for using GOATOOLS and for taking the time to contact us.

**Comment by dvklopfenstein** [comment]
FYI: Newly downloaded GAF files once again have illegal lines, but the format of the illegal line is new (missing middle columns). 

I have updated our code to ignore these lines and will ask @tanghaibao to create a new PyPi version of GOATOOLS.

So if you again see GAF errors, please update your GOATOOLS package.

**Comment by EmilioGarciaMoran** [comment]
I also had troubles with reading a 2.1 gaf file. Optional last two columns make the trouble. They are missing in most lines, but gaf_reader.py exits as soon as the line does not have 17 values. I first tinkered to skip reading those columns. Reading was successful up to 1800 lines, when 16th column was filled. I cut -f 15 my file and it worked. Quick and dirty solutions, I think the code should allow missing values in 16th and 17th columns for 2.x gaf files, IMHO.

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and thank you for taking the time to contact us.

Can you place your gaf file on a Google drive? Or email it to dvklopfenstein@gmail.com

**Comment by harryscholes** [comment]
I'm still having problems loading PomBase GO annotations (ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.pombase.gz) using GOATOOLS 0.8.2 from PyPI:

```python
AssertionError: EXP 17 COLUMNS, SAW 15
```
Everything works fine when I install from git master though.

**Comment by dvklopfenstein** [comment]
@tanghaibao,  Please make a new PyPI version. We saw some new forms of illegal gaf lines (which should be ignored) recently. The GOATOOLS master has the updates, but PyPI does not.

@harryscholes Thank you for taking the time to contact us and thank you for the specific example where you are seeing the error in code from PyPI.

**Comment by tanghaibao** [comment]
@dvklopfenstein pushed to PyPi (v0.8.4) - let me know if anything is wrong. Haibao

**Comment by harryscholes** [comment]
@tanghaibao PyPI version works now, thanks. Do you think it would be worth including tests of loading some popular gaf files in the Travis builds?

**Comment by dvklopfenstein** [comment]
So glad to hear that the PyPI version is working now.

We do have a test that loads ~40 gaf files (tests/test_termcounts_asscs.py). But it is not on our Travis-CI subset of tests because it takes a while to run and causes Travis-CI to timeout. It is a requirement to run by anyone who submits a pull request.

This test was passing. Then some GAF lines started to have an illegal format. We loosened the code to skip those illegal gaf lines. All was well. Then a new way for the gaf lines to be illegal popped up. We adjusted for that too. Hopefully, we are good to go for a while.

Thank you for taking your time to write us and thank you for your interest in GOATOOLS.
